// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLS3Op30iHHddlxhgKW6SlrKduHVU6de4',
    appId: '1:917900094496:web:cb8664832de6ebdd1e2045',
    messagingSenderId: '917900094496',
    projectId: 'book-tracker-chayan1906',
    authDomain: 'book-tracker-chayan1906.firebaseapp.com',
    storageBucket: 'book-tracker-chayan1906.appspot.com',
    measurementId: 'G-DJ4TG4GRZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPuKSh3X4ELyVJa2zz2KwmGPrNU_GigvU',
    appId: '1:917900094496:android:4b6261fd91f0ea301e2045',
    messagingSenderId: '917900094496',
    projectId: 'book-tracker-chayan1906',
    storageBucket: 'book-tracker-chayan1906.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1ve-7yeCh7TnHJunemJadRZyjTGYVEjo',
    appId: '1:917900094496:ios:3cc346ec93099efa1e2045',
    messagingSenderId: '917900094496',
    projectId: 'book-tracker-chayan1906',
    storageBucket: 'book-tracker-chayan1906.appspot.com',
    iosClientId: '917900094496-aonph2bvlcm3rh0buep164od1pe6ui95.apps.googleusercontent.com',
    iosBundleId: 'com.padmanabhasmac.bookTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1ve-7yeCh7TnHJunemJadRZyjTGYVEjo',
    appId: '1:917900094496:ios:3cc346ec93099efa1e2045',
    messagingSenderId: '917900094496',
    projectId: 'book-tracker-chayan1906',
    storageBucket: 'book-tracker-chayan1906.appspot.com',
    iosClientId: '917900094496-aonph2bvlcm3rh0buep164od1pe6ui95.apps.googleusercontent.com',
    iosBundleId: 'com.padmanabhasmac.bookTracker',
  );
}
